# Generated by Django 4.2.6 on 2023-12-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0024_alter_payment_amount_paid_orderaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='email',
            field=models.EmailField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='phone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='pincode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
